#ARG windowsversion=ltsc2016
ARG windowsversion=1809
FROM mcr.microsoft.com/windows:$windowsversion


ENV chocolateyUseWindowsCompression false

RUN powershell -Command \
    Set-ExecutionPolicy Bypass -Force; \
    iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1')); \
    choco feature disable --name showDownloadProgress