FROM windowsserver-chocolatey

RUN powershell -Command \
    New-Item c:\downloads -type directory ;

RUN powershell -Command \
    Set-Variable -Name 'ErrorActionPreference' -Value 'Stop'; \
    choco install qbittorrent --ignore-checksums -y \
    New-Item C:\ProgramData\qBittorrent\config -force -type directory ;

COPY qbittorrent.ini /ProgramData/qBittorrent/

COPY bootstrap.ps1 /
ENTRYPOINT ["powershell", "-ExecutionPolicy", "Unrestricted", "c:\\bootstrap.ps1"]

#environment
WORKDIR /ProgramData/qBittorrent
ENV qbittorrent_port=8080

#metadata
EXPOSE 8080
VOLUME C:\\ProgramData\\qBittorrent\\config C:\\downloads


# docker run --name qbittorrent -d -p 8080:8080 -v D:/DockerVolumes/AppFiles/qbittorent/config:C:/ProgramData/qBittorrent/config -v D:/DockerVolumes/Downloads:C:/ProgramData/qBittorrent/downloads windowsserver-qbittorrent
# docker run --name qbittorrent -it --entrypoint powershell.exe -p 8080:8080 -v D:/DockerVolumes/AppFiles/qbittorent/config:C:/ProgramData/qBittorrent/config -v D:/DockerVolumes/Downloads:C:/ProgramData/qBittorrent/downloads windowsserver-qbittorrent