FROM windowsserver-chocolatey

RUN powershell -Command \
    New-Item c:\media -type directory ; \
    New-Item c:\downloads -type directory ;

RUN powershell -Command \
    Set-Variable -Name 'ErrorActionPreference' -Value 'Stop'; \
    choco install radarr --ignore-checksums -y ;

RUN powershell -Command \
    Copy-Item c:\ProgramData\Radarr\bin\ c:\ -force -recurse ;\
    Rename-Item c:\bin Radarr ;

COPY bootstrap.ps1 /
ENTRYPOINT ["powershell", "-ExecutionPolicy", "Unrestricted", "c:\\bootstrap.ps1"]

#environment
WORKDIR /ProgramData/Radarr
ENV bootstrap_process=C:\\Radarr\\radarr.console.exe
ENV warmup_script=C:\\ProgramData\\Radarr\\warmup_script.ps1

#metadata
LABEL Description="Radarr" Vendor="Radarr"
LABEL maintainer="Chocolatey"

#externals
EXPOSE 7878
VOLUME c:\\ProgramData\\Radarr c:\\media c:\\downloads


# docker run --name radarr -d -p 7878:7878 -v D:/DockerVolumes/AppFiles/radarr:C:/ProgramData/Radarr -v e:\media:c:\media windowsserver-radarr
# docker run --name radarr -it --entrypoint powershell.exe -p 7878:7878 -v D:/DockerVolumes/AppFiles/radarr:C:/ProgramData/Radarr -v e:\media:c:\media windowsserver-radarr