FROM windows-chocolatey

LABEL Description="Plex" Vendor="Plex"
LABEL maintainer="Chocolatey"

EXPOSE 32400 1900/udp 3005 5353/udp 8324 32410/udp 32412/udp 32413/udp 32414/udp 32469

# escape=`

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

#COPY Install-ServerMediaFoundation.ps1 /
#RUN & c:\Install-ServerMediaFoundation.ps1

RUN Set-Variable -Name 'ErrorActionPreference' -Value 'Stop'; \
    choco install plexmediaserver --ignore-checksums -y ; \
    New-Item c:\media -type directory ; \
    New-Item c:\ProgramData\PlexConfig -type directory ;
VOLUME c:\\ProgramData\\PlexConfig c:\\media

COPY bootstrap.ps1 /
WORKDIR /ProgramData/PlexConfig
ENTRYPOINT ["powershell", "-ExecutionPolicy", "Unrestricted", "c:\\bootstrap.ps1"]

# docker run --name plex -d -p 32400:32400 -v D:/DockerVolumes/AppFiles/pms-docker/config:C:/ProgramData/PlexConfig windowsserver-plex
# docker run --name plex -it --entrypoint powershell.exe -p 32400:32400 -v D:/DockerVolumes/AppFiles/pms-docker/config:C:/ProgramData/PlexConfig windowsserver-plex